apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: nodeserver
        image: docker.io/rvteja358/node_jenkinsapp_kubernetes:latest
        ports:
        - containerPort: 4000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: node
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 4000
    nodePort: 31111
